### ISSUE TITLE
Explore VizDoom integration

### ISSUE THREAD

**Issue by nazaruka** [nazaruka/gym-http-api#12]
As part of exploring the code with broader domains, we will be attempting to run these algorithms with VizDoom. Here is [one example](https://github.com/nsavinov/gym-vizdoom) of another person's implementation (may or may not work on Windows)

**Comment by schrum2** [comment]
It would be convenient if we could explore the VizDoom domains as well. Here are some useful links:
https://github.com/shakenes/vizdoomgym
https://github.com/openai/doom-py
https://github.com/nsavinov/gym-vizdoom

Try the approaches that require the least compiling first.

**Comment by schrum2** [comment]
Given the time we have, this is no longer a priority. Closing ...
