### ISSUE TITLE
Get Retro Working

### ISSUE THREAD

**Issue by schrum2** [nazaruka/gym-http-api#14]
It would be awesome to run these domains:
https://github.com/openai/retro
They supposedly work in Windows.

Also, if it works, it looks like it will solve #7 as well.

**Comment by schrum2** [comment]
Running this was shockingly easy:
https://retro.readthedocs.io/en/latest/getting_started.html
Let's see if it is as easy to apply an RL algorithm to it

**Comment by nazaruka** [comment]
(Referencing #7 as well)
I was able to import the Atari ROMs by running `python -m retro.import C:\Users\Admin\Desktop\Southwestern\SCOPE\Files\Repo\atari-py\atari_py\atari_roms`. Now, when I run the central access point file, Python is able to render any one of the Atari environments. Of course, it still has issues with implementing the algorithms

**Comment by schrum2** [comment]
We both have retro working! Of course, now we need to integrate code in our repo with retro
